// Country list with flag emoji + Arabic & English names
export const COUNTRIES = [
  { code: 'IQ', flag: '🇮🇶', ar: 'العراق', en: 'Iraq' },
  { code: 'SA', flag: '🇸🇦', ar: 'السعودية', en: 'Saudi Arabia' },
  { code: 'AE', flag: '🇦🇪', ar: 'الإمارات', en: 'United Arab Emirates' },
  { code: 'KW', flag: '🇰🇼', ar: 'الكويت', en: 'Kuwait' },
  { code: 'QA', flag: '🇶🇦', ar: 'قطر', en: 'Qatar' },
  { code: 'BH', flag: '🇧🇭', ar: 'البحرين', en: 'Bahrain' },
  { code: 'OM', flag: '🇴🇲', ar: 'عُمان', en: 'Oman' },
  { code: 'YE', flag: '🇾🇪', ar: 'اليمن', en: 'Yemen' },
  { code: 'JO', flag: '🇯🇴', ar: 'الأردن', en: 'Jordan' },
  { code: 'SY', flag: '🇸🇾', ar: 'سوريا', en: 'Syria' },
  { code: 'LB', flag: '🇱🇧', ar: 'لبنان', en: 'Lebanon' },
  { code: 'PS', flag: '🇵🇸', ar: 'فلسطين', en: 'Palestine' },
  { code: 'EG', flag: '🇪🇬', ar: 'مصر', en: 'Egypt' },
  { code: 'SD', flag: '🇸🇩', ar: 'السودان', en: 'Sudan' },
  { code: 'LY', flag: '🇱🇾', ar: 'ليبيا', en: 'Libya' },
  { code: 'TN', flag: '🇹🇳', ar: 'تونس', en: 'Tunisia' },
  { code: 'DZ', flag: '🇩🇿', ar: 'الجزائر', en: 'Algeria' },
  { code: 'MA', flag: '🇲🇦', ar: 'المغرب', en: 'Morocco' },
  { code: 'MR', flag: '🇲🇷', ar: 'موريتانيا', en: 'Mauritania' },
  { code: 'SO', flag: '🇸🇴', ar: 'الصومال', en: 'Somalia' },
  { code: 'DJ', flag: '🇩🇯', ar: 'جيبوتي', en: 'Djibouti' },
  { code: 'KM', flag: '🇰🇲', ar: 'جزر القمر', en: 'Comoros' },
  { code: 'TR', flag: '🇹🇷', ar: 'تركيا', en: 'Turkey' },
  { code: 'IR', flag: '🇮🇷', ar: 'إيران', en: 'Iran' },
  { code: 'GB', flag: '🇬🇧', ar: 'المملكة المتحدة', en: 'United Kingdom' },
  { code: 'US', flag: '🇺🇸', ar: 'الولايات المتحدة', en: 'United States' },
  { code: 'CA', flag: '🇨🇦', ar: 'كندا', en: 'Canada' },
  { code: 'FR', flag: '🇫🇷', ar: 'فرنسا', en: 'France' },
  { code: 'DE', flag: '🇩🇪', ar: 'ألمانيا', en: 'Germany' },
  { code: 'IT', flag: '🇮🇹', ar: 'إيطاليا', en: 'Italy' },
  { code: 'ES', flag: '🇪🇸', ar: 'إسبانيا', en: 'Spain' },
  { code: 'NL', flag: '🇳🇱', ar: 'هولندا', en: 'Netherlands' },
  { code: 'SE', flag: '🇸🇪', ar: 'السويد', en: 'Sweden' },
  { code: 'NO', flag: '🇳🇴', ar: 'النرويج', en: 'Norway' },
  { code: 'DK', flag: '🇩🇰', ar: 'الدنمارك', en: 'Denmark' },
  { code: 'BE', flag: '🇧🇪', ar: 'بلجيكا', en: 'Belgium' },
  { code: 'CH', flag: '🇨🇭', ar: 'سويسرا', en: 'Switzerland' },
  { code: 'AT', flag: '🇦🇹', ar: 'النمسا', en: 'Austria' },
  { code: 'GR', flag: '🇬🇷', ar: 'اليونان', en: 'Greece' },
  { code: 'RU', flag: '🇷🇺', ar: 'روسيا', en: 'Russia' },
  { code: 'IN', flag: '🇮🇳', ar: 'الهند', en: 'India' },
  { code: 'PK', flag: '🇵🇰', ar: 'باكستان', en: 'Pakistan' },
  { code: 'BD', flag: '🇧🇩', ar: 'بنغلاديش', en: 'Bangladesh' },
  { code: 'AF', flag: '🇦🇫', ar: 'أفغانستان', en: 'Afghanistan' },
  { code: 'CN', flag: '🇨🇳', ar: 'الصين', en: 'China' },
  { code: 'JP', flag: '🇯🇵', ar: 'اليابان', en: 'Japan' },
  { code: 'KR', flag: '🇰🇷', ar: 'كوريا الجنوبية', en: 'South Korea' },
  { code: 'MY', flag: '🇲🇾', ar: 'ماليزيا', en: 'Malaysia' },
  { code: 'ID', flag: '🇮🇩', ar: 'إندونيسيا', en: 'Indonesia' },
  { code: 'AU', flag: '🇦🇺', ar: 'أستراليا', en: 'Australia' },
  { code: 'NZ', flag: '🇳🇿', ar: 'نيوزيلندا', en: 'New Zealand' },
  { code: 'BR', flag: '🇧🇷', ar: 'البرازيل', en: 'Brazil' },
  { code: 'NG', flag: '🇳🇬', ar: 'نيجيريا', en: 'Nigeria' },
  { code: 'ZA', flag: '🇿🇦', ar: 'جنوب أفريقيا', en: 'South Africa' },
  { code: 'OTHER', flag: '🌐', ar: 'أخرى', en: 'Other' },
]
